baseURL = 'https://funnylookinhat.com/'
languageCode = 'en-us'
title = 'FunnyLookinHat / David Overcash'

disableKinds = ['taxonomy', 'term']

[security]
  [security.exec]
    allow = ['asciidoctor']

[markup.asciidocExt]
  [markup.asciidocExt.attributes]
    toc = "true"
